# Generated by Django 6.0.6 on 2026-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_training_attendance_status_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.IntegerField(default=20),
        ),
    ]
