# Generated by Django 6.0.6 on 2026-06-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_annual_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='casual_leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave')], max_length=20),
        ),
    ]
