# Generated by Django 6.0.6 on 2026-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_casual_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
