# Generated by Django 6.0.6 on 2026-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_projectupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
