# Generated by Django 6.0.6 on 2026-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Weekoff', 'Weekoff')], default='Holiday', max_length=20),
        ),
    ]
