# Generated by Django 6.0.6 on 2026-07-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_holiday_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltracking',
            name='target_achievement',
        ),
        migrations.AddField(
            model_name='goaltracking',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='employees.project'),
        ),
    ]
