# Generated by Django 6.0.6 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_goaltracking_target_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltracking',
            name='type',
        ),
        migrations.AlterField(
            model_name='goaltracking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
