# Generated by Django 6.0.6 on 2026-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='employees.employee'),
        ),
    ]
