# Generated by Django 6.0.6 on 2026-07-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_shift_attendance_late_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='grace_period_minutes',
        ),
    ]
