# Generated by Django 6.0.6 on 2026-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_remove_shift_grace_period_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grace_period_minutes',
            field=models.IntegerField(default=120, help_text='Monthly grace period for late arrivals in minutes'),
        ),
    ]
