# Generated by Django 6.0.6 on 2026-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_employee_grace_period_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='late_penalty_lop_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='severe_late_incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_late_mins',
            field=models.IntegerField(default=0),
        ),
    ]
