# Generated by Django 6.0.6 on 2026-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_shiftrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Unpaid', 'Unpaid Leave')], max_length=20),
        ),
    ]
