# Generated by Django 6.0.6 on 2026-07-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='casual_leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.IntegerField(default=10),
        ),
    ]
