# Generated by Django 6.0.6 on 2026-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_employee_casual_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='maternity_leave_balance',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='employee',
            name='paternity_leave_balance',
            field=models.IntegerField(default=14),
        ),
    ]
