# Generated by Django 6.0.6 on 2026-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_employee_department_old_employee_designation_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='expenses/medical/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='expenses/medical/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Office Supplies', 'Office Supplies'), ('Medical', 'Medical'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
