# Generated by Django 6.0.6 on 2026-07-22 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='module',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Company Event', 'Company Event'), ('Training', 'Training'), ('Other', 'Other')], default='Meeting', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
