# Generated by Django 6.0.6 on 2026-07-22 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_remove_activitylog_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='module',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
