# Generated by Django 6.0.6 on 2026-07-22 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_activitylog_details_activitylog_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('Offer Letter', 'Offer Letter'), ('Experience Certificate', 'Experience Certificate'), ('Relieving Letter', 'Relieving Letter'), ('NOC Certificate', 'NOC Certificate'), ('Custom Letter', 'Custom Letter')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('signatory_name', models.CharField(default='HR Manager', max_length=150)),
                ('signatory_title', models.CharField(default='Head of Human Resources', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_letters', to='employees.employee')),
            ],
        ),
    ]
